Add word analysis
zineland/zine pull request #14
Opened 2022-03-25 16:03 UTC by KernelErr

In this pull request, the word analysis feature is added by using `jieba`.  We count all words whose length is greater than 1 and sort them in a B TreeMap. However, visualization is **not** implemented yet.

Signed-off-by: KernelErr <me@lirui.tech>

2022-03-25 16:16 UTC, KernelErr commented
However, this implementation might not be good enough. `Jieba` only supports Chinese. And it does not support English very well, let alone other languages. :(

2022-03-26 02:27 UTC, Folyd requested changes
Nice, thanks @KernelErr. I think `svg` is the best format for word cloud visualization. If we google `word cloud generator`, you'll find most of it is rendered with `svg`.

2022-03-26 02:27 UTC, Folyd commented on src/entity/season.rs
> +            let words = jieba.cut(&article.markdown, true);
I think we should `strip_markdown` in advance?

2022-03-26 02:27 UTC, Folyd commented on src/entity/season.rs
> +    pub word_count: BTreeMap<String, u32>,
I suggest renaming it to `word_cloud`

2022-03-28 12:42 UTC, KernelErr commented
> Nice, thanks @KernelErr. I think `svg` is the best format for word cloud visualization. If we google `word cloud generator`, you'll find most of it is rendered with `svg`.

Gotcha. I will try to render the word cloud this week. :)

2022-07-26 07:53 UTC, KernelErr commented
Closed due to outdated code. I may work on this in later days.

2022-07-26 07:53 UTC, closed without merging